import { ArrowLeft, Eye, KeyRound, Mail, UserRound } from 'lucide-react'
import type { VistaAplicacion } from '../../app/router'

export function AuthPage({ vista, navegar }: { vista: Extract<VistaAplicacion, 'login' | 'registro' | 'recuperar' | 'verificar'>; navegar: (vista: VistaAplicacion) => void }) {
  const esLogin = vista === 'login'; const esRegistro = vista === 'registro'; const esRecuperar = vista === 'recuperar'; const esVerificar = vista === 'verificar'
  const titulo = esLogin ? 'Ingresa a MAPUC' : esRegistro ? 'Crea tu cuenta' : esRecuperar ? 'Recupera tu acceso' : 'Verifica tu correo'
  const descripcion = esLogin ? 'Usa tu cuenta PUCP para continuar.' : esRegistro ? 'Completa tus datos para explorar el campus.' : esRecuperar ? 'Te enviaremos instrucciones al correo registrado.' : 'Ingresa el código que enviamos a tu correo PUCP.'
  return <main className="auth"><section className="auth-marca"><div><p>MAPUC</p><h1>Tu campus, más cerca.</h1><span>Encuentra lugares, consulta aforo y llega con rutas accesibles.</span></div></section><section className="auth-formulario"><div className="auth-caja">{!esLogin && <button type="button" className="volver" onClick={() => navegar('login')}><ArrowLeft size={18} /> Volver</button>}<p className="eyebrow">Bienvenido a MAPUC</p><h2>{titulo}</h2><p className="subtitulo-auth">{descripcion}</p>{esRegistro && <label>Nombre completo<div className="campo"><UserRound size={18} /><input placeholder="María García" /></div></label>}{!esVerificar && <label>Correo PUCP<div className="campo"><Mail size={18} /><input type="email" placeholder="usuario@pucp.edu.pe" /></div></label>}{(esLogin || esRegistro) && <label>Contraseña<div className="campo"><KeyRound size={18} /><input type="password" placeholder="Mínimo 8 caracteres" /><Eye size={18} /></div></label>}{esVerificar && <label>Código de verificación<div className="campo"><KeyRound size={18} /><input inputMode="numeric" placeholder="000000" /></div></label>}<button type="button" className="primario auth-boton" onClick={() => navegar(esRegistro ? 'verificar' : esRecuperar ? 'verificar' : 'mapa')}>{esLogin ? 'Iniciar sesión' : esRegistro ? 'Crear cuenta' : esRecuperar ? 'Enviar instrucciones' : 'Verificar correo'}</button>{esLogin && <button type="button" className="enlace" onClick={() => navegar('recuperar')}>¿Olvidaste tu contraseña?</button>}<p className="pie-auth">{esLogin ? <>¿Aún no tienes cuenta? <button type="button" onClick={() => navegar('registro')}>Regístrate</button></> : <>¿Ya tienes cuenta? <button type="button" onClick={() => navegar('login')}>Inicia sesión</button></>}</p></div></section></main>
}
